channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - dask
  - cython
  - shapely
  - fiona
  - pyproj
  - six
  - pysal
  - geopandas
  - requests
  - branca
  - jinja2
  - folium
  - seaborn
  - scikit-learn
