channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - cython
  - shapely
  - fiona
  - pyproj
  - six
  - pysal
  - geopandas
  - requests
